export const START_GAME = 'START_GAME';
export const INCREMENT_GAME_COUNTER = 'INCREMENT_GAME_COUNTER';
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const SET_TEXT_MATCH = 'SET_TEXT_MATCH';
export const SET_GAME_STATUS = 'SET_GAME_STATUS';
export const SET_WPM = 'SET_WPM';
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE';
export const RESET_GAME = 'RESET_GAME';
